#!/bin/sh

# Author:				Ahmed Elhori <ahmed@elhori.com>
# License:			GNU GPLv3
# Description:	Select script through dmenu

script="$(\
	cat <<- EOF | dmenu -l 10
	weather
	toggle-picom
	connect-to-tv
EOF
)"

$script
