#!/bin/sh

# Author:       Ahmed Elhori <dev@elhori.com>
# License:      GNU GPLv3
# Description:  Select a script through dmenu

script="$(\
	cat <<- EOF | dmenu -i -l 10
	toggle-compositor
	toggle-eq
	toggle-screenkey
	weather
EOF
)"

"$script"
