#!/bin/sh

# Author:       Ahmed Elhori <dev@elhori.com>
# License:      GNU GPLv3
# Description:  Open video link with youtube-dl and mpv

check_dependency(){
	dep_missing=0
	for x in "$@"; do
		if ! which "$x" >/dev/null 2>&1; then
			echo "$NAME - Error: $x not installed"
			dep_missing=1
		fi
	done

	if [ "$dep_missing" -ne '0' ]; then
		exit 1
	fi
}

prepare(){
	# Set script name
	NAME="$(basename $0)"

	# Set correct browser
	if [ "$PRIVATE_BROWSER" ]; then
		browser="$PRIVATE_BROWSER"
	elif [ "$BROWSER" ]; then
		browser="$BROWSER"
	else
		browser="$(basename "$(xdg-mime query default text/html)" .desktop)"
	fi
}

get_video_quality(){
	quality="$(\
		youtube-dl --list-formats -- "$1" | \
		sed -n '/format code.*resolution/,$p' | \
		sed -n '/audio only/!p' | \
		tail -n +2 | \
		tac | \
		dmenu -p 'Choose Video Quality' -i -l 10)"

	quality_code="$(\
		printf "$quality" | \
		sed -n 's/^\([^ ]*\).*$/\1/p')"

	printf "$quality_code"
}

open_browser(){
	# Open using window manager if available
	if which i3 >/dev/null 2>&1; then
		i3-msg "exec --no-startup-id $browser $1" >/dev/null 2>&1 &
	else
		nohup "$browser" -- "$1" >/dev/null 2>&1 &
	fi
}

run(){
	choice="$( printf 'Best\nOptions\nBrowser' | dmenu -p 'Choose' -i)"

	case "$choice" in
		Browser) open_browser "$1"; return 0;;
		Options) quality="$(get_video_quality $1)";;
		*) quality="$choice";;
	esac

	if [ -z "$quality" ]; then
		echo 'quality not selected' >&2
		return 1
	fi

	message="$(mpv --hwdec=auto --ytdl-format=$quality+bestaudio/best --af=scaletempo2 $1)"

	if [ "$?" != '0' ]; then
		notify-send 'Error' "$message"
	fi
}


main(){
	check_dependency 'mpv' 'youtube-dl' 'dmenu' 'xdg-open'
	prepare "$@"
	run "$@"
}

main "$@"
