#!/bin/sh

# Author:       Ahmed Elhori <dev@elhori.com>
# License:      GNU GPLv3
# Description:  Open rss link

check(){
	# Check arguments
	if [ -z "$1" ]; then
		printf "Usage: $NAME <link>" >&2
		exit 1
	fi
}

prepare(){
	# Set script name
	NAME="$(basename $0)"

	# Set correct browser
	if [ "$PRIVATE_BROWSER" ]; then
		browser="$PRIVATE_BROWSER"
	elif [ "$BROWSER" ]; then
		browser="$BROWSER"
	else
		browser="$(basename $(xdg-mime query default text/html) .desktop)"
	fi
}

run(){
	case "$1" in
		*youtube.com/watch\?v=*) open_video "$1";;
		*odysee.com/@*/*) open_video "$1";;
		*video*.*) open_video "$1";;
		*) open_browser "$1";;
	esac
}

open_video(){
	nohup open-video-link "$1" >/dev/null 2>&1 &
}

open_browser(){
	# Open using window manager if available
	if which i3 >/dev/null 2>&1; then
		i3-msg "exec --no-startup-id $browser $1" >/dev/null 2>&1 &
	else
		nohup "$browser" -- "$1" >/dev/null 2>&1 &
	fi
}

main(){
	check "$@"
	prepare "$@"
	run "$@"
}

main "$@"
