#!/bin/sh

# Author:       Ahmed Elhori <dev@elhori.com>
# License:      GNU GPLv3
# Description:  Toggle audio EQ

if pgrep -x easyeffects; then
	pkill easyeffects
	return
fi

easyeffects --gapplication-service
