#!/bin/sh

# Author:       Ahmed Elhori <dev@elhori.com>
# License:      GNU GPLv3
# Description:  Check weather

get_locaiton(){
	# If "$DISPLAY" not set read stdin instead
	location="$(printf '' | dmenu -p 'Enter location' -i -l 5)"
}

run(){
	"$TERMINAL" -e sh -c 'curl -L https://wttr.in/'"${location}"' && sleep 1000000'
}

main(){
	get_locaiton
	run
}

main "$@"
